#pragma once

#define IDI_APP_ICON 101
#define IDR_EXO2_FONT 201
#define IDR_SOUND_DRS_APPROACHING 301
#define IDR_SOUND_DRS_READY 302
#define IDR_SOUND_PREPARE_STRAIGHT 303
#define IDR_SOUND_STRAIGHT_READY 304
#define IDR_SOUND_LOW_BATTERY 305
#define IDR_SOUND_ERS_FAULT 306
#define IDR_SOUND_DRS_FAULT 307
